### PR TITLE
URLRewrite and data-uri changes

### LINKED ISSUE #74: data-uri rewrite fixes
this is very related also to: https://github.com/i-net-software/jlessc/issues/73

because the data-uri can have the same thing it can just have 

data-ur('folder/image');

but that folder is not really the root where it all starts (the root.less file that imports it all)
this can be already in one folder deep like in issue 73

So what this patch does is look if normally the url would be rewritted
if so then rewrite the url and then try to load it so where the data gets from will be correct
(it will still fallback if that doesn't work)

besides that this patch also doesn't load in the full data if we notice it will be bigger then 32x1024 (then we inline it anyway)

if we inline it as a normal url (because of a failure loading it or because of it is to big)
then make sure again that we use the rewrite url so the full right url is generated from the root on.

also a small patch to support image/webp formats

### PR DESCRIPTION
**Pull request by jcompagner**
these commits fixes: https://github.com/i-net-software/jlessc/issues/74 and https://github.com/i-net-software/jlessc/issues/73

changed also the test so are testing a bit more and really how the urls should end up when looking it all relative to the less file they are in

the last commit is for base64 changes (i run with java8 or java11 and always the base64 stuff is different)

### CODE REVIEW

**Comment by jcompagner** [comment]
this is just very weird, now the test are failing i guess that i fix on my end because i generates different base64 strings..

Why would that be..

**Comment by Horcrux7** [comment]
I am unclear why you touch all the tests? For example the base64 of the data: protocol should not modified.

I can also not accept a pull request that change the behavior that all the test must adapted. It is ok for me to extends a test file with additional use cases. But the existing behavior should not change else there are good reasons. For example a modified behavior of LessC in a newer version. Or the difference has no effect like whitespaces. Or the result are more optimized. etc. I hope you understand what i means.

**Comment by jcompagner** [comment]
i just don't why they are not failing ?
how is that possible? at my local machine the test are all failing because of that

but that is easy to not do, because thats just a seperate commit

Problem was with the rest of the test that they where really wrong
they did not really work they way the should.

as an example this:

https://github.com/i-net-software/jlessc/blob/master/test/com/inet/lib/less/RewriteUrls/subfolder1/subfolder2/sub2.less#L4

that is a rule that is incorrect. for that sub2.less file there is no "subfolder1/image.jpg"
(subfolder2 doesn't have a subfolder1 subfolder)

If you just would compile just "sub2.less" to css.. (as the main css file not included anywhere)
that that image is just broken it is the same as DoesNotExists.jpg:

https://github.com/i-net-software/jlessc/blob/master/test/com/inet/lib/less/RewriteUrls/subfolder1/subfolder2/sub2.less#L6

because for that less file also subfolder1/image.jpg is not there..


the rul that is correct for sub2.less is the first one:
url('../image.jpg'); 

that really goes to something that is there.

for sub2.less to let this one work:

 url3:      url('subfolder1/image.jpg'); 

would be 

 url3:      url('../../subfolder1/image.jpg'); 


So they are all good reasons, except the base64 (which i really don't get why that is different on my machine) the things i modified where because the test where really not ok,  everything should really be relative so the file it self (just as it would be a css that is standalone)

**Comment by jcompagner** [comment]
but yes purely this commit:

https://github.com/i-net-software/jlessc/pull/75/commits/7464447de0b2dbe36355a171252a8130dbbdbeab

should not be applied then.. is there any explanation why i really need that?
else all the test will break for me locally..

**Comment by Horcrux7** [comment]
I have run with lessc version 3.12.2 the follow commands:
```
lessc --rewrite-urls=local main.less
```
```
lessc --rewrite-urls=all main.less
```
and it produce an equally output. That the test is correct. There is a difference for the `off` mode because JLessC use an additional fallback to search the images relative for data-uri. But this is not a problem.

**Pull request closed without merging**
