### PR TITLE
the url-rewrite=all patch so it works the same as lessc compiler

### PR DESCRIPTION
**Pull request by jcompagner**
in "all" mode it ignores the root and urls with a scheme
just like the lessc compiler also does.

### CODE REVIEW

**Comment by jcompagner** [comment]
i will double check what lessc now really outputs (with all the added tests) with what this patch now generates
i see that lessc outputs "./" in front of files where jlessc does without that (that shouldn't really be any problem, that is the same thing)

but i see with a data-uri it doesn't inline for some reason the /main.jpg test that i added.. i will check that

**Comment by jcompagner** [comment]
[RewriteUrls.zip](https://github.com/i-net-software/jlessc/files/5634573/RewriteUrls.zip)

If you want to test master against all the added test of this pull request 

You see if you run that with jlessc your self it fails on all of them now,
because of data-uri stuff (over all 3 scenarios), the urls are not normalized, root urls are not handles well and "http://test.com" is completely gone.

**Comment by Horcrux7** [comment]
You have already merge different things in one pull request. This make the analyze difficult and will take some time.

**Comment by jcompagner** [comment]
except this one: https://github.com/i-net-software/jlessc/pull/76/commits/2008941c499752128d77dc5edef1b06e2fcb3995
that really shouldn't be in (i can remove if you want) this, its a bit that i just saw by accident

But the rest are all kind of all belong to each other, they are very related, because url or data-uri are should both behaves the same (the url rewrite that url(xx) uses is also used (or not depending on the mode) for data-uri

**Pull request merged**
